const cityAreaList = {
  "Abu Dhabi": [
    {"City name": "Abu Dhabi Golf Club"},
    {"City name": "Abu Dhabi International Airport"},
    {"City name": "Abu Dhabi Mall"},
    {"City name": "Abu Dhabi University"},
    {"City name": "Abu Samrah"},
    {"City name": "Airport Termial 2"},
    {"City name": "Airport Termial 3"},
    {"City name": "Ajban Farms"},
    {"City name": "Al Adlah"},
    {"City name": "Al Ajban"},
    {"City name": "Al Ameriya"},
    {"City name": "Al Asheesh"},
    {"City name": "Al Bahiya"},
    {"City name": "Al Bandar"},
    {"City name": "Al Bateen"},
    {"City name": "Al Bateen Beach"},
    {"City name": "Al Bihouth"},
    {"City name": "Al Danah"},
    {"City name": "Al Dhafra Air Base"},
    {"City name": "Al Dhafrah"},
    {"City name": "Al Dhahir"},
    {"City name": "Al Falah"},
    {"City name": "Al Fayah"},
    {"City name": "Al Forsan Village"},
    {"City name": "Al Ghazal Golf Club"},
    {"City name": "Al Ghuwaifat"},
    {"City name": "Al Gurm West"},
    {"City name": "Al Haffar"},
    {"City name": "Al Hudairiyat Island"},
    {"City name": "Al Jubail Island"},
    {"City name": "Al Karamah"},
    {"City name": "Al Khalidiyah"},
    {"City name": "Al Khubeirah"},
    {"City name": "Al Lissaily"},
    {"City name": "Al Lulu Island"},
    {"City name": "Al Mafraq Workers City"},
    {"City name": "Al Manhal"},
    {"City name": "Al Maqta"},
    {"City name": "Al Markaziyah West"},
    {"City name": "Al Markhaniyyah"},
    {"City name": "Al Me'rad"},
    {"City name": "Al Mina"},
    {"City name": "Al Muntazah"},
    {"City name": "Al Musalla"},
    {"City name": "Al Mushrif"},
    {"City name": "Al Mushrif Mall"},
    {"City name": "Al Muzoon"},
    {"City name": "Al Nahda East"},
    {"City name": "Al Nahdah"},
    {"City name": "Al Nahyan"},
    {"City name": "Al Qurm"},
    {"City name": "Al Raha Beach"},
    {"City name": "Al Raha Creek"},
    {"City name": "Al Rahbah"},
    {"City name": "Al Ras Al Akhdar"},
    {"City name": "Al Rayyana"},
    {"City name": "Al Razeen"},
    {"City name": "Al Reef"},
    {"City name": "Al Reem Island"},
    {"City name": "Al Rowdah"},
    {"City name": "Al Rumaila"},
    {"City name": "Al Ruwais"},
    {"City name": "Al Sa'adah"},
    {"City name": "Al Sad"},
    {"City name": "Al Salamat"},
    {"City name": "Al Samha"},
    {"City name": "Al Seef"},
    {"City name": "Al Shahama"},
    {"City name": "Al Shaleela"},
    {"City name": "Al Shamkha East"},
    {"City name": "Al Shamkhah"},
    {"City name": "Al Sharia"},
    {"City name": "Al Shawamekh"},
    {"City name": "Al Shiwayb"},
    {"City name": "Al Taweelah"},
    {"City name": "Al Wahda Mall"},
    {"City name": "Al Wahdah"},
    {"City name": "Al Wathba Cycle Track"},
    {"City name": "Al Wathba North"},
    {"City name": "Al Wathba Wetland"},
    {"City name": "Al Wathbah"},
    {"City name": "Al Za'faran St"},
    {"City name": "Al Zaab"},
    {"City name": "Al Zahiyah"},
    {"City name": "Al Zeina"},
    {"City name": "Al-mihawi"},
    {"City name": "Asab"},
    {"City name": "Bain Al Jesrain"},
    {"City name": "Baniyas"},
    {"City name": "Baniyas East"},
    {"City name": "Baniyas West"},
    {"City name": "Bateen Mall"},
    {"City name": "Bawabat Abu Dhabi"},
    {"City name": "Baynunah Tower"},
    {"City name": "Beda Zayed"},
    {"City name": "Bu Hasa"},
    {"City name": "Capital Centre"},
    {"City name": "Delma Mall"},
    {"City name": "Dhaharat Al-teeb"},
    {"City name": "Embassies District"},
    {"City name": "Etihad Rail"},
    {"City name": "Ghantout"},
    {"City name": "Ghiyathi"},
    {"City name": "Hadbat Al Za'faranah"},
    {"City name": "Hamdan Street - Al Hosn"},
    {"City name": "Hameem"},
    {"City name": "Icad 1"},
    {"City name": "ICAD 2"},
    {"City name": "Jarn Yafour"},
    {"City name": "Jazeerat Al Maryah"},
    {"City name": "Jazeerat Al Shelaylah"},
    {"City name": "Jebel Dhanna"},
    {"City name": "Khalidiyah Mall"},
    {"City name": "Khalifa City"},
    {"City name": "Khalifa City B"},
    {"City name": "Khalifa City C"},
    {"City name": "Khalifa Park 1"},
    {"City name": "Khalifa University - San Campus"},
    {"City name": "Khor Al Maqta'a"},
    {"City name": "Madinat Zayed Shopping Centre"},
    {"City name": "Mafraq"},
    {"City name": "Mafraq Industrial Area"},
    {"City name": "Mangrove National Park"},
    {"City name": "Mangrove Village"},
    {"City name": "Marina Mall"},
    {"City name": "Masdar City"},
    {"City name": "Mazayed Village"},
    {"City name": "Mazyad Mall"},
    {"City name": "Mina Zayed"},
    {"City name": "Mohamed Bin Zayed City"},
    {"City name": "Musaffah"},
    {"City name": "Mussafah Community"},
    {"City name": "Mussafah Industrial"},
    {"City name": "Nahil"},
    {"City name": "Nareel Island"},
    {"City name": "New Al Nahdha"},
    {"City name": "Nujoom Island"},
    {"City name": "Qareen Al Aish"},
    {"City name": "Qasr Al Bahr"},
    {"City name": "Rawdat Al-reef"},
    {"City name": "Rimah"},
    {"City name": "Saadiyat Island"},
    {"City name": "Samaliyah Island"},
    {"City name": "Sas Al Nakhl Island"},
    {"City name": "Sas Al Nakhl Village"},
    {"City name": "SE45"},
    {"City name": "Sector 15"},
    {"City name": "Shahamah"},
    {"City name": "Shakhbout City"},
    {"City name": "Sheikh Khalifa Medical City"},
    {"City name": "Sheikh Zayed Cricket Stadium"},
    {"City name": "Sheikh Zayed Grand Mosque Center"},
    {"City name": "Sweihan"},
    {"City name": "The Gate District"},
    {"City name": "Umm Yifenah Island"},
    {"City name": "W56"},
    {"City name": "Watani Residential"},
    {"City name": "Yas Island"},
    {"City name": "Yas Marina Circuit"},
    {"City name": "Zayed City"},
    {"City name": "Zayed Military City"},
    {"City name": "Zayed Military Hospital"},
    {"City name": "Zayed Sports City"},
    {"City name": "Zayed Univesity"},
    {"City name": "Zeraa Island"},
    {"City name": "Zone 1"}
  ],
  "Ajman": [
    {"City name": "Ajman Free Zone"},
    {"City name": "Ajman Industrial 2"},
    {"City name": "Al Alia"},
    {"City name": "Al Amerah"},
    {"City name": "Al Bustan - Ajman"},
    {"City name": "Al Hamidiya 1"},
    {"City name": "Al Hamidiya 2"},
    {"City name": "Al Hamriyah Free Zone"},
    {"City name": "Al Helio 1"},
    {"City name": "Al Helio 2"},
    {"City name": "Al Jerf 1"},
    {"City name": "Al Jerf 2"},
    {"City name": "Al Jerf Industrial 1"},
    {"City name": "Al Jerf Industrial 2"},
    {"City name": "Al Manamah"},
    {"City name": "Al Muaihat 1"},
    {"City name": "Al Muntazi 1"},
    {"City name": "Al Muntazi 2"},
    {"City name": "Al Muwaihat 2"},
    {"City name": "Al Muwaihat 3"},
    {"City name": "Al Nakhil 1"},
    {"City name": "Al Nuaimia"},
    {"City name": "Al Nuaimia 1"},
    {"City name": "Al Owan"},
    {"City name": "Al Raqaib 1"},
    {"City name": "Al Raqaib 2"},
    {"City name": "Al Rashidiya 2"},
    {"City name": "Al Rashidiya 3"},
    {"City name": "Al Rawda 1"},
    {"City name": "Al Rawda 2"},
    {"City name": "Al Rawdha 3"},
    {"City name": "Al Rumailah"},
    {"City name": "Al Talla 1"},
    {"City name": "Al Tallah 2"},
    {"City name": "Al Zahya"},
    {"City name": "Free Zone"},
    {"City name": "Hamidiya"},
    {"City name": "Industrial Area"},
    {"City name": "Industrial Area 1"},
    {"City name": "Meshairef"}
  ],
  "Al Ain": [
    {"City name": "Ain Al Fayda"},
    {"City name": "Al Aflaj"},
    {"City name": "Al Ain Hospital"},
    {"City name": "Al Ain Industrial Area"},
    {"City name": "Al Ain International Airport"},
    {"City name": "Al Ain Oasis"},
    {"City name": "Al Andalus Compound"},
    {"City name": "Al Bateen"},
    {"City name": "Al Dahmaa"},
    {"City name": "Al Dhahir"},
    {"City name": "Al Dhahrah"},
    {"City name": "Al Faqa"},
    {"City name": "Al Fou'ah"},
    {"City name": "Al Hayer"},
    {"City name": "Al Hili"},
    {"City name": "Al Iqabiyyah"},
    {"City name": "Al Jahili"},
    {"City name": "Al Jimi"},
    {"City name": "Al Khaznah"},
    {"City name": "Al Khibeesi"},
    {"City name": "Al Khirayr"},
    {"City name": "Al Maqam"},
    {"City name": "Al Markhaniya"},
    {"City name": "Al Mas'oudi"},
    {"City name": "Al Mnaizfah"},
    {"City name": "Al Mnaizlah"},
    {"City name": "Al Mu'tarid"},
    {"City name": "Al Murabaa"},
    {"City name": "Al Mutaw'ah"},
    {"City name": "Al Muwaiji"},
    {"City name": "Al Neyadat"},
    {"City name": "Al Owainah"},
    {"City name": "Al Qattara"},
    {"City name": "Al Qisais"},
    {"City name": "Al Qou'a"},
    {"City name": "Al Rawdah"},
    {"City name": "Al Rawdah Al Sharqiyah"},
    {"City name": "Al Ruwaikah"},
    {"City name": "Al Ruwaydat"},
    {"City name": "Al Salamat"},
    {"City name": "Al Sarouj"},
    {"City name": "Al Shabhat Plaza"},
    {"City name": "Al Shuaibah"},
    {"City name": "Al Tiwayyah"},
    {"City name": "Al Yahar"},
    {"City name": "Al Yahar North"},
    {"City name": "Al Yahar South"},
    {"City name": "Ameriya"},
    {"City name": "Asharij"},
    {"City name": "Bad' Bint Sa'oud"},
    {"City name": "Bida Bint Saud Masjid"},
    {"City name": "Bu Kirayyah"},
    {"City name": "Central District"},
    {"City name": "Civic Center"},
    {"City name": "Falaj Hazzaa"},
    {"City name": "Ghireebah"},
    {"City name": "Hai Khalid"},
    {"City name": "Industrial Area"},
    {"City name": "Jabel Hafeet"},
    {"City name": "Khatm Al Shiklah"},
    {"City name": "Majlood - Al Muwaiji"},
    {"City name": "Malaqit"},
    {"City name": "Masakin"},
    {"City name": "Mazyad"},
    {"City name": "Mutaredh Oasis"},
    {"City name": "Neima Mall"},
    {"City name": "Remah"},
    {"City name": "Shareat Al Muwaiji"},
    {"City name": "Sweihan"},
    {"City name": "Tawam"},
    {"City name": "Um Ghafah"},
    {"City name": "Zakhir"},
    {"City name": "Zayed Mosque Town"}
  ],
  "Dubai": [
    {"City name": "Abu Hail"},
    {"City name": "Academic City"},
    {"City name": "Airport Termial 1"},
    {"City name": "Al Aweer"},
    {"City name": "Al Bada'a"},
    {"City name": "Al Baraha"},
    {"City name": "Al Barari"},
    {"City name": "Al Barsha"},
    {"City name": "Al Barsha 1"},
    {"City name": "Al Barsha 2"},
    {"City name": "Al Barsha 3"},
    {"City name": "Al Barsha South 2"},
    {"City name": "Al Barsha South 4"},
    {"City name": "Al Barsha South 5"},
    {"City name": "Al Barsha South1"},
    {"City name": "Al Furjan"},
    {"City name": "Al Hamriya Port"},
    {"City name": "Al Hebiah"},
    {"City name": "Al Hebiah Fourth"},
    {"City name": "Al Jaddaf"},
    {"City name": "Al Jafiliya"},
    {"City name": "Al Karama"},
    {"City name": "Al Khaibaisi"},
    {"City name": "Al Khawaneej 1"},
    {"City name": "Al Khawaneej 2"},
    {"City name": "Al Kifaf"},
    {"City name": "Al Lailis Nature Reserve"},
    {"City name": "Al Lisaili"},
    {"City name": "Al Maktoum International Airport"},
    {"City name": "Al Manara"},
    {"City name": "Al Mankhool"},
    {"City name": "Al Mizhar 1"},
    {"City name": "Al Mizhar 2"},
    {"City name": "Al Murar"},
    {"City name": "Al Muteena"},
    {"City name": "Al Nahda 1"},
    {"City name": "Al Nahda 2 - Dubai"},
    {"City name": "Al Quasis 2"},
    {"City name": "Al Quasis Ind. 2"},
    {"City name": "Al Quasis Ind. 3"},
    {"City name": "Al Quasis Ind. 4"},
    {"City name": "Al Quasis Ind. 5"},
    {"City name": "Al Quoz"},
    {"City name": "Al Quoz 1"},
    {"City name": "Al Quoz 2"},
    {"City name": "Al Quoz 3"},
    {"City name": "Al Quoz 4"},
    {"City name": "Al Quoz Industrial"},
    {"City name": "Al Quoz Industrial Area 2"},
    {"City name": "Al Quoz Industrial Area 3"},
    {"City name": "Al Quoz Industrial Area 4"},
    {"City name": "Al Qurda, Camel Race"},
    {"City name": "Al Qusais 1"},
    {"City name": "Al Qusais 2"},
    {"City name": "Al Qusais 3"},
    {"City name": "Al Qusais Industrial Area"},
    {"City name": "Al Qusais Industrial Area 1"},
    {"City name": "Al Raffa"},
    {"City name": "Al Ras"},
    {"City name": "Al Rashidiya - Dubai"},
    {"City name": "Al Rigga"},
    {"City name": "Al Sabkha - Dubai"},
    {"City name": "Al Safa 1"},
    {"City name": "Al Safa 2"},
    {"City name": "Al Satwa"},
    {"City name": "Al Sufouh 1"},
    {"City name": "Al Thanyah"},
    {"City name": "Al Thanyah Mall"},
    {"City name": "Al Twar 1"},
    {"City name": "Al Twar 2"},
    {"City name": "Al Twar 3"},
    {"City name": "Al Waha"},
    {"City name": "Al Waheda"},
    {"City name": "Al Warqa"},
    {"City name": "Al Warqa 1"},
    {"City name": "Al Warqa 2"},
    {"City name": "Al Warqa 3"},
    {"City name": "Al Warqa 4"},
    {"City name": "Al Wasl"},
    {"City name": "Arabian Ranches"},
    {"City name": "Bab Al Shams"},
    {"City name": "Barsha Heights"},
    {"City name": "Bur Dubai"},
    {"City name": "Burj Khalifa"},
    {"City name": "Business Bay"},
    {"City name": "City Centre Me'aisem"},
    {"City name": "Deira"},
    {"City name": "Deira City Centre"},
    {"City name": "Difc - Trade Centre"},
    {"City name": "Discovery Garden"},
    {"City name": "Downtown Dubai"},
    {"City name": "Downtown Jabal Ali"},
    {"City name": "Dragon Mart"},
    {"City name": "Dubai Design Distric"},
    {"City name": "Dubai Festival City"},
    {"City name": "Dubai International Airport"},
    {"City name": "Dubai Internet City"},
    {"City name": "Dubai Investments Park"},
    {"City name": "Dubai Mall"},
    {"City name": "Dubai Marina"},
    {"City name": "Dubai Maritime City"},
    {"City name": "Dubai Media City"},
    {"City name": "Dubai Outlet Mall"},
    {"City name": "Dubai Production City"},
    {"City name": "Dubai Silicon Oasis"},
    {"City name": "Dubai World Central"},
    {"City name": "Dubai World Trade Centre"},
    {"City name": "Emaar Business Park"},
    {"City name": "Emirates Hills"},
    {"City name": "Festival City"},
    {"City name": "Garhoud"},
    {"City name": "Global Village"},
    {"City name": "Golf City"},
    {"City name": "Greens"},
    {"City name": "Hamriya"},
    {"City name": "Hatta"},
    {"City name": "Hor Al Anz"},
    {"City name": "Hor Al Anz East"},
    {"City name": "Hudaiba"},
    {"City name": "Ibn Battuta Mall"},
    {"City name": "International City"},
    {"City name": "International City 2"},
    {"City name": "Jebel Ali Free Zone"},
    {"City name": "Jebel Ali Free Zone - Jabal Ali 3"},
    {"City name": "Jebel Ali Free Zone - Jebel Ali 2"},
    {"City name": "Jebel Ali Industrial Area"},
    {"City name": "Jumeira Lakes"},
    {"City name": "Jumeirah"},
    {"City name": "Jumeirah 1"},
    {"City name": "Jumeirah 2"},
    {"City name": "Jumeirah 3"},
    {"City name": "Jumeirah Lake Towers"},
    {"City name": "Jumeirah Village"},
    {"City name": "Knowledge Village"},
    {"City name": "Lahbab"},
    {"City name": "Layan"},
    {"City name": "Living Legends"},
    {"City name": "Majan"},
    {"City name": "Mall Of The Emirates"},
    {"City name": "Marina Mall"},
    {"City name": "Meadows"},
    {"City name": "Millenium States Villa"},
    {"City name": "Mirdif"},
    {"City name": "Motor City"},
    {"City name": "Mudon"},
    {"City name": "Muhaisanah 1"},
    {"City name": "Muhaisanah 2"},
    {"City name": "Muhaisanah 3"},
    {"City name": "Muhaisanah 4"},
    {"City name": "Nad Al Sheba"},
    {"City name": "Nad Al Sheba 1"},
    {"City name": "Nad Al Sheba 2"},
    {"City name": "Nad Al Sheba 3"},
    {"City name": "Nad Al Sheba 4"},
    {"City name": "Nadd Al Hamar"},
    {"City name": "Nadd Hessa, Silicon Oasis"},
    {"City name": "Naif"},
    {"City name": "Oud Al Muteena 1"},
    {"City name": "Oud Al Muteena 2"},
    {"City name": "Oud Metha"},
    {"City name": "Palm Jumeirah"},
    {"City name": "Ras Al Khor"},
    {"City name": "Ras Al Khor Ind. 1"},
    {"City name": "Ras Al Khor Ind. 3"},
    {"City name": "Remraam"},
    {"City name": "Riggat Al Buteen"},
    {"City name": "Sports City"},
    {"City name": "Springs"},
    {"City name": "Springs 4"},
    {"City name": "Sustainable City"},
    {"City name": "The Lakes"},
    {"City name": "Trade Centre"},
    {"City name": "Umm Al Sheif"},
    {"City name": "Umm Hurair 1"},
    {"City name": "Umm Hurair 2"},
    {"City name": "Umm Ramoul"},
    {"City name": "Umm Suqeim 1"},
    {"City name": "Umm Suqeim 2"},
    {"City name": "Umm Suqeim 3"},
    {"City name": "Wadi Al Amardi"},
    {"City name": "Wadi Al Safa"},
    {"City name": "Warsan 2"},
    {"City name": "Warsan 3"},
    {"City name": "Za'abeel 1"},
    {"City name": "Za'abeel 2"}
  ],
  "Fujairah": [
    {"City name": "Abadilah"},
    {"City name": "Al Aqah"},
    {"City name": "Al Bidya"},
    {"City name": "Al Bithnah"},
    {"City name": "Al Halah"},
    {"City name": "Al Hayl"},
    {"City name": "Al Ittihad"},
    {"City name": "Al Owaid"},
    {"City name": "Al Qurayya"},
    {"City name": "Anajaimat - Dibba Rd"},
    {"City name": "City Centre Fujairah"},
    {"City name": "Dahir"},
    {"City name": "Dhadna"},
    {"City name": "Dibba"},
    {"City name": "Dibba Al Fujairah"},
    {"City name": "Dibba Al Hisn"},
    {"City name": "Dibba Beach"},
    {"City name": "Fujairah City Outer"},
    {"City name": "Fujairah Free Zone Authority"},
    {"City name": "Fujairah Hospital"},
    {"City name": "Fujairah International Airport"},
    {"City name": "Fujairah Municipality"},
    {"City name": "Fujairah Port"},
    {"City name": "Ghub"},
    {"City name": "Hatin"},
    {"City name": "Industrial Area"},
    {"City name": "Jabal Safad"},
    {"City name": "Jabal Umm Al-farfar"},
    {"City name": "Kalba"},
    {"City name": "M-14"},
    {"City name": "Madhab"},
    {"City name": "Merashid"},
    {"City name": "Mirbah"},
    {"City name": "Murbah Beach"},
    {"City name": "Qidfa"},
    {"City name": "Sakamkam"},
    {"City name": "Sharm"},
    {"City name": "Shawka"},
    {"City name": "Suwayfah"},
    {"City name": "Wadi Al Wurayah"},
    {"City name": "Wadi Helo"},
    {"City name": "Zubara"}
  ],
  "Ras Al Khaimah": [
    {"City name": "Adhen Village"},
    {"City name": "Al Darbi Janiyah"},
    {"City name": "Al Dhait"},
    {"City name": "Al Dhait North"},
    {"City name": "Al Dhait South"},
    {"City name": "Al Fahalain"},
    {"City name": "Al Ghail"},
    {"City name": "Al Ghubb"},
    {"City name": "Al Hamra Village"},
    {"City name": "Al Hudaibah"},
    {"City name": "Al Jazirah Al Hamra"},
    {"City name": "Al Jeer"},
    {"City name": "Al Juwais"},
    {"City name": "Al Kharran"},
    {"City name": "Al Mairid"},
    {"City name": "Al Mamourah"},
    {"City name": "Al Nadiyah"},
    {"City name": "Al Nakheel"},
    {"City name": "Al Nudood"},
    {"City name": "Al Qurm"},
    {"City name": "Al Qusaidat"},
    {"City name": "Al Rams"},
    {"City name": "Al Riffa"},
    {"City name": "Al Sall"},
    {"City name": "Al Seer"},
    {"City name": "Al Sharisha, Al Mataf"},
    {"City name": "Al Soor"},
    {"City name": "Al Uraibi, Al Manara"},
    {"City name": "Al-turfa"},
    {"City name": "Awafi"},
    {"City name": "Baqal"},
    {"City name": "Bin Majid Beach Hotel"},
    {"City name": "Dafan Al Khor"},
    {"City name": "Dahan"},
    {"City name": "Ghalilah"},
    {"City name": "Hamra - Rak"},
    {"City name": "Hamraniyah"},
    {"City name": "Jebel Jais Mountain"},
    {"City name": "Julphar"},
    {"City name": "Khatt"},
    {"City name": "Khorkhuwair"},
    {"City name": "Khuzam"},
    {"City name": "Liwa Badr"},
    {"City name": "Marjan Island"},
    {"City name": "Masafi"},
    {"City name": "Mina Al Arab"},
    {"City name": "Ras Al Khaima Old City"},
    {"City name": "Ras Al Khaimah Economic Zone"},
    {"City name": "Ras Al Khaimah International Airport"},
    {"City name": "Ras Al Selaab"},
    {"City name": "Seih Al Burairat"},
    {"City name": "Seih Al Ghubb"},
    {"City name": "Seih Al Hudaibah"},
    {"City name": "Seih Shihyar"},
    {"City name": "Sha'am"},
    {"City name": "Shamal Haqueel"},
    {"City name": "Shawka"},
    {"City name": "Sidroh"},
    {"City name": "Sidroh 2"},
    {"City name": "Siji"},
    {"City name": "Suhaim"},
    {"City name": "Wadi Bih Area"}
  ],
  "Sharjah": [
    {"City name": "Abu Shagara"},
    {"City name": "Agricultural Falah"},
    {"City name": "Al Abar"},
    {"City name": "Al Atain"},
    {"City name": "Al Azra"},
    {"City name": "Al Batayeh"},
    {"City name": "Al Bu Daniq"},
    {"City name": "Al Dhaid"},
    {"City name": "Al Falah Suburb"},
    {"City name": "Al Falaj"},
    {"City name": "Al Fayha"},
    {"City name": "Al Fisht"},
    {"City name": "Al Ghafia"},
    {"City name": "Al Gharb"},
    {"City name": "Al Ghubaiba"},
    {"City name": "Al Ghuwair"},
    {"City name": "Al Goaz"},
    {"City name": "Al Hamriyah"},
    {"City name": "Al Hazannah"},
    {"City name": "Al Heerah Suburb"},
    {"City name": "Al Houmah"},
    {"City name": "Al Jazzat"},
    {"City name": "Al Jubail"},
    {"City name": "Al Jurainah 1"},
    {"City name": "Al Jurainah 2"},
    {"City name": "Al Jurainah 3"},
    {"City name": "Al Jurainah 4"},
    {"City name": "Al Khaledia Suburb"},
    {"City name": "Al Khan"},
    {"City name": "Al Khezamia"},
    {"City name": "Al Layyeh Suburb"},
    {"City name": "Al Madam"},
    {"City name": "Al Majarrah"},
    {"City name": "Al Majaz 1"},
    {"City name": "Al Majaz 2"},
    {"City name": "Al Majaz 3"},
    {"City name": "Al Mamzar"},
    {"City name": "Al Manakh"},
    {"City name": "Al Mareija"},
    {"City name": "Al Meena Street"},
    {"City name": "Al Mirgab"},
    {"City name": "Al Musalla"},
    {"City name": "Al Nahda"},
    {"City name": "Al Nasserya"},
    {"City name": "Al Nekhailat"},
    {"City name": "Al Noof 1"},
    {"City name": "Al Noof 2"},
    {"City name": "Al Noof 3"},
    {"City name": "Al Noof 4"},
    {"City name": "Al Nuaimia 1"},
    {"City name": "Al Nud"},
    {"City name": "Al Qadisia"},
    {"City name": "Al Qasimia"},
    {"City name": "Al Qulaya'ah"},
    {"City name": "Al Rahmaniya"},
    {"City name": "Al Rahmaniya 1"},
    {"City name": "Al Rahmaniya 2"},
    {"City name": "Al Rahmaniya 3"},
    {"City name": "Al Rahmaniya 4"},
    {"City name": "Al Rahmaniya 5"},
    {"City name": "Al Rahmaniya 6"},
    {"City name": "Al Rahmaniya 7"},
    {"City name": "Al Rahmaniya 8"},
    {"City name": "Al Ramaqiya"},
    {"City name": "Al Ramla - East"},
    {"City name": "Al Ramla - West"},
    {"City name": "Al Ramtha"},
    {"City name": "Al Rifa'a"},
    {"City name": "Al Rifa'ah"},
    {"City name": "Al Riqa Suburb"},
    {"City name": "Al Sabkha"},
    {"City name": "Al Seef - Sharjah"},
    {"City name": "Al Shahba"},
    {"City name": "Al Sharq"},
    {"City name": "Al Shuwaihean"},
    {"City name": "Al Soor"},
    {"City name": "Al Suyoh Suburb"},
    {"City name": "Al Sweihat"},
    {"City name": "Al Taawun"},
    {"City name": "Al Tala'a"},
    {"City name": "Al Wasit Area"},
    {"City name": "Al Yarmook"},
    {"City name": "Al Yash"},
    {"City name": "Al Zubair Orchards"},
    {"City name": "American University of Sharjah"},
    {"City name": "Barashi"},
    {"City name": "Bu Tina"},
    {"City name": "Buheira Corniche"},
    {"City name": "City Center -shj"},
    {"City name": "Cricket Stadium Area"},
    {"City name": "Darari"},
    {"City name": "Dasman"},
    {"City name": "Flag Island"},
    {"City name": "Gold Souq-new"},
    {"City name": "Gold Souq-old"},
    {"City name": "Halwan Suburb"},
    {"City name": "Hamriya Free Zone"},
    {"City name": "Hayawa"},
    {"City name": "Industrial Area 1"},
    {"City name": "Industrial Area 11"},
    {"City name": "Industrial Area 13"},
    {"City name": "Industrial Area 15"},
    {"City name": "Industrial Area 2"},
    {"City name": "Industrial Area 4"},
    {"City name": "Industrial Area 5"},
    {"City name": "Industrial Area 6"},
    {"City name": "Industrial Area 8"},
    {"City name": "Industrial Area 9"},
    {"City name": "Khalid Port"},
    {"City name": "Khor Fakkan"},
    {"City name": "Luluyah Beach"},
    {"City name": "Majaz"},
    {"City name": "Maleha"},
    {"City name": "Mansoura"},
    {"City name": "Maysaloon"},
    {"City name": "Muwafjah"},
    {"City name": "Muwaileh Commercial"},
    {"City name": "Muwailih"},
    {"City name": "Muzairah"},
    {"City name": "Qarayen"},
    {"City name": "Qarayen 1"},
    {"City name": "Qarayen 2"},
    {"City name": "Qarayen 3"},
    {"City name": "Qarayen 4"},
    {"City name": "Qarayen 5"},
    {"City name": "Qasmiya Hospital"},
    {"City name": "Rolla"},
    {"City name": "Sahara Centre"},
    {"City name": "Samnan"},
    {"City name": "Sharjah Airport Freezone"},
    {"City name": "Sharjah Clock Tower"},
    {"City name": "Sharjah Industrial"},
    {"City name": "Sharjah Industrial Area 10"},
    {"City name": "Sharjah Industrial Area 12"},
    {"City name": "Sharjah Industrial Area 3"},
    {"City name": "Sharjah Industrial Area 7"},
    {"City name": "Sharjah International Airport"},
    {"City name": "Sharjah Sports Club"},
    {"City name": "Sharqan"},
    {"City name": "Souq Al Jubail"},
    {"City name": "The Sharjah Equestrian & Racing Club"},
    {"City name": "Um Altaraffa"},
    {"City name": "Um Fannain"},
    {"City name": "University City"},
    {"City name": "University Of Sharjah"}
  ],
  "Umm Al Quwain": [
    {"City name": "Al Aahad"},
    {"City name": "Al Abrab"},
    {"City name": "Al Arabi Sports And Cultural Club"},
    {"City name": "Al Dar Al Baida - A"},
    {"City name": "Al Dar Al Baida - B"},
    {"City name": "Al Haditha"},
    {"City name": "Al Hawiyah"},
    {"City name": "Al Humrah"},
    {"City name": "Al Humrah - A"},
    {"City name": "Al Humrah - B"},
    {"City name": "Al Humrah - C"},
    {"City name": "Al Humrah - D"},
    {"City name": "Al Khor"},
    {"City name": "Al Limghadar"},
    {"City name": "Al Maidan"},
    {"City name": "Al Raas"},
    {"City name": "Al Raas - A"},
    {"City name": "Al Raas - B"},
    {"City name": "Al Raas - C"},
    {"City name": "Al Raas - D"},
    {"City name": "Al Rafaah"},
    {"City name": "Al Ramlah - B"},
    {"City name": "Al Ramlah - C"},
    {"City name": "Al Ramlah -a"},
    {"City name": "Al Raudah"},
    {"City name": "Al Riqqah"},
    {"City name": "Al Salamah - B"},
    {"City name": "Al Salamah - C"},
    {"City name": "Al Salamah A"},
    {"City name": "Defence Camp"},
    {"City name": "Falaj Al Mualla"},
    {"City name": "Green Belt"},
    {"City name": "Masjid Al Mazroui"},
    {"City name": "Old Town Area"},
    {"City name": "Sheikh Khalifa General Hospital"},
    {"City name": "Uaq New Industrial Area"},
    {"City name": "Umm Al Quwain Airpor"},
    {"City name": "Umm Al Quwain Hospital"},
    {"City name": "Umm Al Quwain Industrial City Authority"},
    {"City name": "Umm Al Quwain Marina"}
  ],
  "Western Region": [
    {"City name": "Al Hamra"},
    {"City name": "Al Mirfa"},
    {"City name": "Al Rafiq"},
    {"City name": "Al Ruwais"},
    {"City name": "Al Sila"},
    {"City name": "Bateen Liwa"},
    {"City name": "Bu Ghar"},
    {"City name": "Bu Hasa"},
    {"City name": "Dalma Island"},
    {"City name": "Ghayathi"},
    {"City name": "Gheweifat"},
    {"City name": "Habshan"},
    {"City name": "Jananah Island"},
    {"City name": "Jazeerat Abu Al Abyad"},
    {"City name": "Jebel Dhanna"},
    {"City name": "Kayyam"},
    {"City name": "Khannur"},
    {"City name": "Mezairaa"},
    {"City name": "Qareen Al Aish"},
    {"City name": "Qassabi"},
    {"City name": "Ras Ghurb Island"},
    {"City name": "Sir Baniyas Island"},
    {"City name": "Tarif"},
    {"City name": "Umm Hosn"},
    {"City name": "Zayed City"},
    {"City name": "Zeraa Island"}
  ]
};
