org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.defaults.buildfeatures.buildconfig=true
kotlin.compiler.execution.strategy=daemon
kotlin.options.freeCompilerArgs=-Xlint:unchecked -Xlint:deprecation
kotlin.compiler.version=2.1.0
android.native.enable16KPageSupport=true